# Generated by Django 2.1.7 on 2019-04-21 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='Current_GPA',
            field=models.FloatField(default='2.9', validators=[django.core.validators.MaxValueValidator(4.0)]),
        ),
    ]
