# Generated by Django 2.1.7 on 2019-04-26 18:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='Coauthor',
        ),
        migrations.RemoveField(
            model_name='research',
            name='Current_Program_Year',
        ),
        migrations.AddField(
            model_name='paper',
            name='List_of_Authors',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='Publish_Term',
            field=models.CharField(blank=True, choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=6),
        ),
        migrations.AddField(
            model_name='paper',
            name='Publish_Year',
            field=models.IntegerField(blank=True, choices=[(2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='Current_GPA',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='research',
            name='Defence_Status',
            field=models.CharField(choices=[('Expected', 'Expected'), ('Passed', 'Passed'), ('Not Passed', 'Not Passed')], default='Expected', max_length=10),
        ),
        migrations.AddField(
            model_name='research',
            name='Proposal_Status',
            field=models.CharField(choices=[('Expected', 'Expected'), ('Passed', 'Passed'), ('Not Passed', 'Not Passed')], default='Expected', max_length=10),
        ),
        migrations.AddField(
            model_name='research',
            name='Thesis_Committee',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Author',
            field=models.ForeignKey(blank=True, db_column='name', on_delete=django.db.models.deletion.PROTECT, to='registration.studentName'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Status_of_Paper',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Under Revision', 'Under Revision'), ('Published', 'Published')], max_length=15),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10),
        ),
        migrations.AlterField(
            model_name='research',
            name='Defense',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='research',
            name='Proposal',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='submissiontrack',
            name='Current_Program_Year',
        ),
        migrations.AlterUniqueTogether(
            name='submissiontrack',
            unique_together={('username', 'questionnaire_for')},
        ),
    ]
