# Generated by Django 2.1.7 on 2019-04-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontrack',
            name='Current_Program_Year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='Defense',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='research',
            name='Proposal',
            field=models.DateField(),
        ),
    ]
