# Generated by Django 2.1.7 on 2019-04-22 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_research_current_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='Coauthor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Status_of_Paper',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Under Revision', 'Under Revision'), ('Published', 'Published')], max_length=15),
        ),
        migrations.AlterField(
            model_name='research',
            name='Current_GPA',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AlterField(
            model_name='research',
            name='Current_Program_Year',
            field=models.IntegerField(default='1', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='submissiontrack',
            name='Current_Program_Year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
