# Generated by Django 2.1.7 on 2019-04-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorwhitelist',
            name='name',
        ),
    ]
